version: "3.8"

services:
  db:
    image: postgres:13
    container_name: drug_postgres
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB:       drug_profile
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:     ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout:  5s
      retries:  5
    restart: always

  app:
    build:
      context: ./backend/drug
      dockerfile: Dockerfile
    container_name: drug_app
    ports:
      - "8080:8080"
    environment:

      SPRING_DATASOURCE_URL:                            jdbc:postgresql://db:5432/drug_profile
      SPRING_DATASOURCE_USERNAME:                       postgres
      SPRING_DATASOURCE_PASSWORD:                       1234
      SPRING_JPA_HIBERNATE_DDL_AUTO:                    update
      SPRING_JPA_SHOW_SQL:                              "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:       "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:          org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  pgdata:
