version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: drug_profile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - backend

  spring:
    build:
      context: ./backend/drug
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/drug_profile
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - backend

networks:
  backend:
    driver: bridge